export const ROUTER = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  INTERVIEW: '/interview',
  MOCK_INTERVIEW: '/mock-interview',
  MOCK_INTERVIEW_FORM_BASED: '/mock-interview/form-based',
  MOCK_INTERVIEW_CV_BASED: '/mock-interview/cv-based',
  MOCK_INTERVIEW_CV_JD_BASED: '/mock-interview/cv-jd-upload',
  AI_INTERVIEWER_SELECTION: '/ai-interviewer-selection',
  INTERVIEW_CALL: '/interview-call',
  AI_CHAT: '/ai-chat',
  AI_CHAT_CONVERSATION: '/ai-chat/conversation',
  AI_RESUME_ANALYZER: '/ai-resume-analyzer',
  AI_RESUME_ANALYZER_RESULT: '/ai-resume-analyzer/result',
  AI_ROADMAP: '/ai-roadmap',
  AI_ROADMAP_DETAIL: '/ai-roadmap/detail',
  AI_INTERVIEWER_DETAIL: '/ai-interviewer-detail',
  SETTINGS: '/settings',
  PROFILE: '/profile',
};
